filebeat.inputs:
  - type: log
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "StrongPassword123"
  ssl.verification_mode: none
  allow_older_versions: true
